### PR TITLE
Added Template for Custom link previews

### PR DESCRIPTION
**Pull request by shariqmalik**
So that you can provide personalised previews on links when sending them over Slack, Discord, etc., I provided a template for custom OG meta tags.

A straight redirect to the given url will occur immediately on the website.

**Link Previews:**

Discord:

Slack:

### CODE REVIEW

**Comment by thewhiteh4t** [comment]
awesome work! @shariqmalik I will merge very soon

**Comment by HeryAE** [comment]
how to add the template?

**Comment by thewhiteh4t** [comment]
@HeryAE I will add soon

**Comment by HeryAE** [comment]
thank you, waiting for the update 😁

**Review by fishke22 — APPROVED** [review]

**Pull request merged**
