### PR TITLE
Code Refactoring to reduce the number of files to ease template creation

### PR DESCRIPTION
**Pull request by Resousse**
Hello,

I propose this large refactoring of files, to reduce its number, to ease the creation of new templates:
- Removal of files containing test data
- Core JS and PHP files that will be copied dynamically --> link between template and core files is done via `information()` and `locate()` javascript function
- Harmonization of module work, via systematic _temp file and mod_*.py
- Add of a dedicated documentation page to explain how to create your own templates
- Edit of the DockerFile to be container ready (dependencies + expose port 8080 + direct launch of seeker.py at container startup)

### CODE REVIEW

**Comment by Resousse** [comment]
Hello @thewhiteh4t ,
Thanks for merging my past PR.
I agree this one will be more difficult to review... :)

I will have still couple of PR to push:
- Obfuscation of code to ensure a code reader will have some trouble to understand it without running the code

**Comment by thewhiteh4t** [comment]
@Resousse obfuscation is not required

**Comment by Resousse** [comment]
@thewhiteh4t, to avoid possible ambiguity : this PR doesn't contain any code obfuscation feature, it's just a code refactoring.

**Comment by thewhiteh4t** [comment]
@Resousse yess I will review soon :D

**Pull request merged**
